# Generated by Django 3.1.2 on 2020-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(),
        ),
    ]
